### PR TITLE
Gin Cocktails/Format improvements

### PR DESCRIPTION
**Pull request by nickcannariato**
Not sure if you want something as intense as this, but this is A-G of the Gin recipes I've amassed over the last 5 years. Additionally, because I'm a massive cocktail nerd, I added some educational stuff to explain the history and derivatives of the spirit.

The pre-existing gin cocktails you had listed are still present, they've just been reformatted to match the rest of my additions.

### CODE REVIEW

**Comment by nickcannariato** [comment]
Also, just because it's a huge commit, I didn't remove any of the cocktails you already had merged, I merely re-formatted them. I don't desire to completely take over your repo, merely offer some improvements if you're still looking for them.

**Comment by aviau** [comment]
I'm definitely bookmarking this,

**Comment by nickcannariato** [comment]
Took time this evening to type up the complete recipe list. If you want this merged in I'll do a pull request for the other recipe lists I have as soon as they're put together.

**Comment by balevine** [comment]
I'm gonna just merge this without reading it. I trust you.

**Comment by nickcannariato** [comment]
@balevine Glad you finally got around to this 😆

**Comment by balevine** [comment]
😬

**Pull request merged**
